# Generated by Django 2.2.5 on 2019-12-22 20:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorProfileInfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+?9?1?\\d{10}')])),
                ('address', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredVisitorEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.TimeField()),
                ('check_out_time', models.TimeField()),
                ('time_stamp', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Host')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.VisitorProfileInfo')),
            ],
        ),
    ]
